Practice
Minki-Kim95/Python_coaching pull request #3
Opened 2019-09-23 14:26 UTC by Minki-Kim95

질문: pylint를 쓸때 main.py의 app같은 이름도 uppercase로 바꾸라고 하고 그러는데 이런 이름까지도 완벽하게 pylint형식에 맞춰야 하나요??

2019-09-23 14:52 UTC, keeyong commented
> 질문: pylint를 쓸때 main.py의 app같은 이름도 uppercase로 바꾸라고 하고 그러는데 이런 이름까지도 완벽하게 pylint형식에 맞춰야 하나요??

아주 좋은 질문입니다. 이게 함수 밖에서 정의된 변수들은 상수라고 생각해서 알아보기 쉽게 다 대문자로 하라는 건데 무시해도 됩니다. 이건 파이썬 커뮤니티내에서도 다른 의견들이 많은 스타일 가이드입니다

2019-09-23 14:54 UTC, keeyong commented on week2/requirements.txt
> +Flask
이렇게 적어도 되기는 되는데 지금 사용한 버전까지 적어볼래요? 어떤 경우에는 특정 버전만 동작가능한 경우도 있어서 requirements.txt에는 보통 모듈뿐만 아니라 원하는 버전까지 적는게 일반적입니다.

그리고 이렇게 requirements.txt가 있을 경우 거기 있는 모든 파이썬 모듈들을 한번 설치하고 싶다면 어떻게 할 수 있는지도 알아내서 여기에 reply로 적어주세요.

2019-09-23 14:54 UTC, keeyong requested changes
아주 빠르게 잘 했습니다. 마이너한 커멘트 했습니다.

2019-09-24 01:16 UTC, Minki-Kim95 commented on week2/requirements.txt
> +Flask
다시 찾아보니까

이 명령어로 작업한 모듈을 그대로 requirements.txt로 옮길 수 있었고
```
pip freeze > requirements.txt
```

이 명령어로 requirements.txt의 모듈들을 설치 할 수 있었습니다
```
pip install -r requirements.txt
```

2019-09-24 01:21 UTC, merged

2019-09-24 02:14 UTC, keeyong commented
requirements.txt 아주 잘 했습니다!