Practice
Minki-Kim95/Python_coaching pull request #7
Opened 2019-10-07 04:58 UTC by Minki-Kim95

database 정보는 보안상의 이유로 생략했습니다

파일 이름은 각각 assignment1, assignment2 입니다

최고점수의 기준은 가장 적은 missletter를 한것으로 정했습니다

2019-10-07 06:28 UTC, keeyong requested changes
바쁜 일정에 수고 많이 하셨습니다!

2019-10-07 06:28 UTC, keeyong commented on week3/assignment1.py
> +f.close()
이걸 별도의 함수로 정의해서 로딩하는 걸로 변경해보세요. 그리고 파일 관련 코드에는 try except를 사용하는 것이 좋은 습관이니 그것도 적용해보세요. 파일이 로딩 안될 경우 디폴트 단어로 하는 등의 예외작업이 가능할 수 있겠죠

2019-10-07 06:28 UTC, keeyong commented on week3/assignment1.py
> +                f.close()
여기도 전체적으로 파일 관련 코드 부분을 try except로 처리해보기 바랍니다.

2019-10-07 06:28 UTC, keeyong commented on week3/requirements.txt
> +WTForms==2.2.1
sqlite 관련한 라인을 추가하기 바랍니다

2019-10-07 06:28 UTC, keeyong commented on week3/assignment2.py
> +    words.append(row[1])
앞서와 마찬가지로 함수로 떼어내고 try except를 적용해보세요. 그리고 words 테이블의 경우 CREATE TABLE과 같은 SQL로 생성하고 INSERT INTO와 같은 SQL로 내용을 채웠을 텐데 그 코드들을 같이 저장해주면 좋습니다. sql과 같은 폴더를 만들고 거기 words_create.sql, words_population.sql과 같은 파일로 그 정보들을 저장해보세요.

2019-10-07 06:28 UTC, keeyong commented on week3/assignment2.py
> +    words.append(row[1])
읽어들이는 형태를 보면 words 테이블에 word 필드말고 뭔가 하나가 더 있는 것 같은데 뭔가요? 물론 words_create.sql과 words_population.sql 업로드되면 분명히 알 수 있겠습니다만

2019-10-08 01:35 UTC, Minki-Kim95 commented on week3/requirements.txt
> +WTForms==2.2.1
급하게 하다보니까 sqlite를 사용하지 않고 컴퓨터에 로컬로 mysql을 돌리고 거기서 가져오는 식으로 하였습니다 앞으로 과제를 진행할때 딱히 필요한거 같지는 않아서 일단 이대로 병합하겠습니다

2019-10-08 01:39 UTC, Minki-Kim95 commented on week3/assignment2.py
> +    words.append(row[1])
try except 적용 하였고 CREATE TABLE하고 INSERT INTO는 이 답글 달고 다음 과제 시작 전에 except문에 넣어서 진행해 보겠습니다

같은 폴더에 sql파일이 없는 이유는 mysql을 로컬 서버로 돌리고 거기에 접속하여 해서 그런 것입니다 sqlite를 써서 db파일을 읽는건 나중에 해보도록 하겠습니다

words table에 word말고는 id밖에 없습니다

2019-10-08 04:32 UTC, merged